apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: musicdb
  POSTGRES_USER: musicuser
  POSTGRES_PASSWORD: musicpassword
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"
